cp -rf ../../PituMotionDemo/PituMotionDemo/Frameworks/FilterEngine.bundle .
cp -rf ../../PituMotionDemo/PituMotionDemo/Frameworks/YoutuBeauty/PE.dat .
cp -rf ../../PituMotionDemo/PituMotionDemo/Frameworks/YoutuBeauty/ufa.bundle .
cp -rf ../../PituMotionDemo/PituMotionDemo/Frameworks/YoutuBeauty/youtubeauty.bundle .
cp -rf ../../PituMotionDemo/PituMotionDemo/YTFaceSDK.licence .
cp -rf ../../PituMotionDemo/PituMotionDemo/MaterialManager.* .
cp -rf ../../PituMotionDemo/PituMotionDemo/MCPackageDownloadTask.* .
cp -rf ../../PituMotionDemo/PituMotionDemo/MCCameraDynamicView.* .
cp -rf ../../PituMotionDemo/PituMotionDemo/MCTip.* .
cp -rf ../../PituMotionDemo/PituMotionDemo/Additions .
cp -rf ../../PituMotionDemo/PituMotionDemo/Resource .
