# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'
install! 'cocoapods', :disable_input_output_paths => true
use_frameworks!

def tx_UGCKit(subName)
 pod 'UGCKit', :path => 'UGCKit/UGCKit.podspec', :subspecs => ["#{subName}"]
end

target 'XiaoShiPinApp' do
  pod "AFNetworking"
  tx_UGCKit 'UGC'
  pod 'BeautySettingKit', :path => 'BeautySettingKit/BeautySettingKit.podspec'
  pod 'xmagickit', :path => 'xmagickit/xmagickit.podspec'
  pod "MJRefresh"
  pod "MBProgressHUD"
  pod "SDWebImage", '5.19.4'
  pod 'FURenderKit_nama', '8.13.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
